name: rivelinrobotics/deploy-aws-cdk-stack
description: Deploys a Stack to AWS using the Cloud Development Kit (CDK)
inputs:
  stack-pattern:
    description: A pattern matching the ID of the Stack to deploy
    required: true
  ephemeral:
    description: Destroys the Stack at the end of the workflow
    required: false
    default: false
  parameters:
    description: CfnParameters of the form `k1=v1 k2=v2 ...`
    required: false
    default: ""
  app-file:
    description: The path to the CDK app file
    required: false
    default: "app.py"
runs:
  using: docker
  image: Dockerfile
  entrypoint: /deploy.sh
  post-entrypoint: /destroy.sh
  post-if: always()
  args:
    - ${{ inputs.stack-id }}
    - ${{ inputs.parameters }}
    - ${{ inputs.app-file }}
